[
    { "country": "United Arab Emirates", "country_code": "+971" },
    { "country": "Afghanistan", "country_code": "+93" },
    { "country": "Albania", "country_code": "+355" },
    { "country": "Armenia", "country_code": "+374" },
    { "country": "Angola", "country_code": "+244" },
    { "country": "Argentina", "country_code": "+54" },
    { "country": "Austria", "country_code": "+43" },
    { "country": "Australia", "country_code": "+61" },
    { "country": "Azerbaijan", "country_code": "+994" },
    { "country": "Bangladesh", "country_code": "+880" },
    { "country": "Belgium", "country_code": "+32" },
    { "country": "Burkina Faso", "country_code": "+226" },
    { "country": "Bulgaria", "country_code": "+359" },
    { "country": "Bahrain", "country_code": "+973" },
    { "country": "Burundi", "country_code": "+257" },
    { "country": "Benin", "country_code": "+229" },
    { "country": "Brunei Darussalam", "country_code": "+673" },
    { "country": "Bolivia", "country_code": "+591" },
    { "country": "Brazil", "country_code": "+55" },
    { "country": "Botswana", "country_code": "+267" },
    { "country": "Belarus", "country_code": "+375" },
    { "country": "Canada", "country_code": "+1" },
    { "country": "Congo", "country_code": "+242" },
    { "country": "Switzerland", "country_code": "+41" },
    { "country": "Ivory Coast", "country_code": "+225" },
    { "country": "Chile", "country_code": "+56" },
    { "country": "Cameroon", "country_code": "+237" },
    { "country": "China", "country_code": "+86" },
    { "country": "Colombia", "country_code": "+57" },
    { "country": "Costa Rica", "country_code": "+506" },
    { "country": "Czech Republic", "country_code": "+420" },
    { "country": "Germany", "country_code": "+49" },
    { "country": "Denmark", "country_code": "+45" },
    { "country": "Dominican Republic", "country_code": "+1" },
    { "country": "Algeria", "country_code": "+213" },
    { "country": "Ecuador", "country_code": "+593" },
    { "country": "Estonia", "country_code": "+372" },
    { "country": "Egypt", "country_code": "+20" },
    { "country": "Eritrea", "country_code": "+291" },
    { "country": "Spain", "country_code": "+34" },
    { "country": "Ethiopia", "country_code": "+251" },
    { "country": "Finland", "country_code": "+358" },
    { "country": "France", "country_code": "+33" },
    { "country": "Gabon", "country_code": "+241" },
    { "country": "United Kingdom", "country_code": "+44" },
    { "country": "Georgia", "country_code": "+995" },
    { "country": "French Guiana", "country_code": "+594" },
    { "country": "Ghana", "country_code": "+233" },
    { "country": "Gambia", "country_code": "+220" },
    { "country": "Greece", "country_code": "+30" },
    { "country": "Guatemala", "country_code": "+502" },
    { "country": "Guinea-Bissau", "country_code": "+245" },
    { "country": "Hong Kong", "country_code": "+852" },
    { "country": "Honduras", "country_code": "+504" },
    { "country": "Croatia", "country_code": "+385" },
    { "country": "Haiti", "country_code": "+509" },
    { "country": "Hungary", "country_code": "+36" },
    { "country": "Indonesia", "country_code": "+62" },
    { "country": "Ireland", "country_code": "+353" },
    { "country": "Israel", "country_code": "+972" },
    { "country": "India", "country_code": "+91" },
    { "country": "Iraq", "country_code": "+964" },
    { "country": "Italy", "country_code": "+39" },
    { "country": "Jamaica", "country_code": "+1" },
    { "country": "Jordan", "country_code": "+962" },
    { "country": "Japan", "country_code": "+81" },
    { "country": "Kenya", "country_code": "+254" },
    { "country": "Cambodia", "country_code": "+855" },
    { "country": "South Korea", "country_code": "+82" },
    { "country": "Kuwait", "country_code": "+965" },
    { "country": "Laos", "country_code": "+856" },
    { "country": "Lebanon", "country_code": "+961" },
    { "country": "Sri Lanka", "country_code": "+94" },
    { "country": "Liberia", "country_code": "+231" },
    { "country": "Lesotho", "country_code": "+266" },
    { "country": "Lithuania", "country_code": "+370" },
    { "country": "Luxembourg", "country_code": "+352" },
    { "country": "Latvia", "country_code": "+371" },
    { "country": "Libya", "country_code": "+218" },
    { "country": "Morocco", "country_code": "+212" },
    { "country": "Monaco", "country_code": "+377" },
    { "country": "Moldova", "country_code": "+373" },
    { "country": "Madagascar", "country_code": "+261" },
    { "country": "Macedonia", "country_code": "+389" },
    { "country": "Mali", "country_code": "+223" },
    { "country": "Myanmar", "country_code": "+95" },
    { "country": "Mongolia", "country_code": "+976" },
    { "country": "Mauritania", "country_code": "+222" },
    { "country": "The Republic of Malta", "country_code": "+356" },
    { "country": "Malawi", "country_code": "+265" },
    { "country": "Mexico", "country_code": "+52" },
    { "country": "Malaysia", "country_code": "+60" },
    { "country": "Mozambique", "country_code": "+258" },
    { "country": "Namibia", "country_code": "+264" },
    { "country": "Niger", "country_code": "+227" },
    { "country": "Nigeria", "country_code": "+234" },
    { "country": "Nicaragua", "country_code": "+505" },
    { "country": "Netherlands", "country_code": "+31" },
    { "country": "Norway", "country_code": "+47" },
    { "country": "Nepal", "country_code": "+977" },
    { "country": "New Zealand", "country_code": "+64" },
    { "country": "Oman", "country_code": "+968" },
    { "country": "Panama", "country_code": "+507" },
    { "country": "Peru", "country_code": "+51" },
    { "country": "Papua New Guinea", "country_code": "+675" },
    { "country": "Philippines", "country_code": "+63" },
    { "country": "Pakistan", "country_code": "+92" },
    { "country": "Poland", "country_code": "+48" },
    { "country": "Puerto Rico", "country_code": "+1" },
    { "country": "Portugal", "country_code": "+351" },
    { "country": "Paraguay", "country_code": "+595" },
    { "country": "Qatar", "country_code": "+974" },
    { "country": "Romania", "country_code": "+40" },
    { "country": "Serbia", "country_code": "+381" },
    { "country": "Russia", "country_code": "+7" },
    { "country": "Rwanda", "country_code": "+250" },
    { "country": "Saudi Arabia", "country_code": "+966" },
    { "country": "Sudan", "country_code": "+249" },
    { "country": "Sweden", "country_code": "+46" },
    { "country": "Singapore", "country_code": "+65" },
    { "country": "Slovenia", "country_code": "+386" },
    { "country": "Slovakia", "country_code": "+421" },
    { "country": "Sierra Leone", "country_code": "+232" },
    { "country": "Senegal", "country_code": "+221" },
    { "country": "Somalia", "country_code": "+252" },
    { "country": "South Sudan", "country_code": "+211" },
    { "country": "El Salvador", "country_code": "+503" },
    { "country": "Eswatini", "country_code": "+268" },
    { "country": "Chad", "country_code": "+235" },
    { "country": "Togo", "country_code": "+228" },
    { "country": "Thailand", "country_code": "+66" },
    { "country": "Tajikistan", "country_code": "+992" },
    { "country": "Turkmenistan", "country_code": "+993" },
    { "country": "Tunisia", "country_code": "+216" },
    { "country": "Taiwan", "country_code": "+886" },
    { "country": "Tanzania", "country_code": "+255" },
    { "country": "Ukraine", "country_code": "+380" },
    { "country": "Uganda", "country_code": "+256" },
    { "country": "United States", "country_code": "+1" },
    { "country": "Uruguay", "country_code": "+598" },
    { "country": "Uzbekistan", "country_code": "+998" },
    { "country": "Venezuela", "country_code": "+58" },
    { "country": "Vietnam", "country_code": "+84" },
    { "country": "Yemen", "country_code": "+967" },
    { "country": "South Africa", "country_code": "+27" },
    { "country": "Zambia", "country_code": "+26" }
]