// export const CURRENCY = [
//     { "value": "AED", "label": "United Arab Emirates Dirham (AED)" },
//     { "value": "AFN", "label": "Afghan Afghani (AFN)" },
//     { "value": "ALL", "label": "Albanian Lek (ALL)" },
//     { "value": "AMD", "label": "Armenian Dram (AMD)" },
//     { "value": "ANG", "label": "Netherlands Antillean Guilder (ANG)" },
//     { "value": "AOA", "label": "Angolan Kwanza (AOA)" },
//     { "value": "ARS", "label": "Argentine Peso (ARS)" },
//     { "value": "AUD", "label": "Australian Dollar (AUD)" },
//     { "value": "AWG", "label": "Aruban Florin (AWG)" },
//     { "value": "AZN", "label": "Azerbaijani Manat (AZN)" },
//     { "value": "BAM", "label": "Bosnia-Herzegovina Convertible Mark (BAM)" },
//     { "value": "BBD", "label": "Barbadian Dollar (BBD)" },
//     { "value": "BDT", "label": "Bangladeshi Taka (BDT)" },
//     { "value": "BGN", "label": "Bulgarian Lev (BGN)" },
//     { "value": "BHD", "label": "Bahraini Dinar (BHD)" },
//     { "value": "BIF", "label": "Burundian Franc (BIF)" },
//     { "value": "BMD", "label": "Bermudian Dollar (BMD)" },
//     { "value": "BND", "label": "Brunei Dollar (BND)" },
//     { "value": "BOB", "label": "Bolivian Boliviano (BOB)" },
//     { "value": "BRL", "label": "Brazilian Real (BRL)" },
//     { "value": "BSD", "label": "Bahamian Dollar (BSD)" },
//     { "value": "BTN", "label": "Bhutanese Ngultrum (BTN)" },
//     { "value": "BWP", "label": "Botswana Pula (BWP)" },
//     { "value": "BYN", "label": "Belarusian Ruble (BYN)" },
//     { "value": "BZD", "label": "Belize Dollar (BZD)" },
//     { "value": "CAD", "label": "Canadian Dollar (CAD)" },
//     { "value": "CDF", "label": "Congolese Franc (CDF)" },
//     { "value": "CHF", "label": "Swiss Franc (CHF)" },
//     { "value": "CLP", "label": "Chilean Peso (CLP)" },
//     { "value": "CNY", "label": "Chinese Yuan (CNY)" },
//     { "value": "COP", "label": "Colombian Peso (COP)" },
//     { "value": "CRC", "label": "Costa Rican Colón (CRC)" },
//     { "value": "CUC", "label": "Cuban Convertible Peso (CUC)" },
//     { "value": "CUP", "label": "Cuban Peso (CUP)" },
//     { "value": "CVE", "label": "Cape Verdean Escudo (CVE)" },
//     { "value": "CZK", "label": "Czech Koruna (CZK)" },
//     { "value": "DJF", "label": "Djiboutian Franc (DJF)" },
//     { "value": "DKK", "label": "Danish Krone (DKK)" },
//     { "value": "DOP", "label": "Dominican Peso (DOP)" },
//     { "value": "DZD", "label": "Algerian Dinar (DZD)" },
//     { "value": "EGP", "label": "Egyptian Pound (EGP)" },
//     { "value": "ERN", "label": "Eritrean Nakfa (ERN)" },
//     { "value": "ETB", "label": "Ethiopian Birr (ETB)" },
//     { "value": "EUR", "label": "Euro (EUR)" },
//     { "value": "FJD", "label": "Fijian Dollar (FJD)" },
//     { "value": "FKP", "label": "Falkland Islands Pound (FKP)" },
//     { "value": "GBP", "label": "British Pound Sterling (GBP)" },
//     { "value": "GEL", "label": "Georgian Lari (GEL)" },
//     { "value": "GHS", "label": "Ghanaian Cedi (GHS)" },
//     { "value": "GIP", "label": "Gibraltar Pound (GIP)" },
//     { "value": "GMD", "label": "Gambian Dalasi (GMD)" },
//     { "value": "GNF", "label": "Guinean Franc (GNF)" },
//     { "value": "GTQ", "label": "Guatemalan Quetzal (GTQ)" },
//     { "value": "GYD", "label": "Guyanese Dollar (GYD)" },
//     { "value": "HKD", "label": "Hong Kong Dollar (HKD)" },
//     { "value": "HNL", "label": "Honduran Lempira (HNL)" },
//     { "value": "HRK", "label": "Croatian Kuna (HRK)" },
//     { "value": "HTG", "label": "Haitian Gourde (HTG)" },
//     { "value": "HUF", "label": "Hungarian Forint (HUF)" },
//     { "value": "IDR", "label": "Indonesian Rupiah (IDR)" },
//     { "value": "ILS", "label": "Israeli New Shekel (ILS)" },
//     { "value": "INR", "label": "Indian Rupee (INR)" },
//     { "value": "IQD", "label": "Iraqi Dinar (IQD)" },
//     { "value": "IRR", "label": "Iranian Rial (IRR)" },
//     { "value": "ISK", "label": "Icelandic Króna (ISK)" },
//     { "value": "JMD", "label": "Jamaican Dollar (JMD)" },
//     { "value": "JOD", "label": "Jordanian Dinar (JOD)" },
//     { "value": "JPY", "label": "Japanese Yen (JPY)" },
//     { "value": "KES", "label": "Kenyan Shilling (KES)" },
//     { "value": "KGS", "label": "Kyrgyzstani Som (KGS)" },
//     { "value": "KHR", "label": "Cambodian Riel (KHR)" },
//     { "value": "KMF", "label": "Comorian Franc (KMF)" },
//     { "value": "KRW", "label": "South Korean Won (KRW)" },
//     { "value": "KWD", "label": "Kuwaiti Dinar (KWD)" },
//     { "value": "KYD", "label": "Cayman Islands Dollar (KYD)" },
//     { "value": "KZT", "label": "Kazakhstani Tenge (KZT)" },
//     { "value": "LAK", "label": "Lao Kip (LAK)" },
//     { "value": "LBP", "label": "Lebanese Pound (LBP)" },
//     { "value": "LKR", "label": "Sri Lankan Rupee (LKR)" },
//     { "value": "LRD", "label": "Liberian Dollar (LRD)" },
//     { "value": "LSL", "label": "Lesotho Loti (LSL)" },
//     { "value": "LYD", "label": "Libyan Dinar (LYD)" },
//     { "value": "MAD", "label": "Moroccan Dirham (MAD)" },
//     { "value": "MDL", "label": "Moldovan Leu (MDL)" },
//     { "value": "MKD", "label": "Macedonian Denar (MKD)" },
//     { "value": "MMK", "label": "Myanmar Kyat (MMK)" },
//     { "value": "MNT", "label": "Mongolian Tögrög (MNT)" },
//     { "value": "MOP", "label": "Macanese Pataca (MOP)" },
//     { "value": "MRU", "label": "Mauritanian Ouguiya (MRU)" },
//     { "value": "MUR", "label": "Mauritian Rupee (MUR)" },
//     { "value": "MVR", "label": "Maldivian Rufiyaa (MVR)" },
//     { "value": "MWK", "label": "Malawian Kwacha (MWK)" },
//     { "value": "MXN", "label": "Mexican Peso (MXN)" },
//     { "value": "MYR", "label": "Malaysian Ringgit (MYR)" },
//     { "value": "MZN", "label": "Mozambican Metical (MZN)" },
//     { "value": "NAD", "label": "Namibian Dollar (NAD)" },
//     { "value": "NGN", "label": "Nigerian Naira (NGN)" },
//     { "value": "NIO", "label": "Nicaraguan Córdoba (NIO)" },
//     { "value": "NOK", "label": "Norwegian Krone (NOK)" },
//     { "value": "NPR", "label": "Nepalese Rupee (NPR)" },
//     { "value": "NZD", "label": "New Zealand Dollar (NZD)" },
//     { "value": "OMR", "label": "Omani Rial (OMR)" },
//     { "value": "PAB", "label": "Panamanian Balboa (PAB)" },
//     { "value": "PEN", "label": "Peruvian Sol (PEN)" },
//     { "value": "PGK", "label": "Papua New Guinean Kina (PGK)" },
//     { "value": "PHP", "label": "Philippine Peso (PHP)" },
//     { "value": "PKR", "label": "Pakistani Rupee (PKR)" },
//     { "value": "PLN", "label": "Polish Złoty (PLN)" },
//     { "value": "PYG", "label": "Paraguayan Guaraní (PYG)" },
//     { "value": "QAR", "label": "Qatari Riyal (QAR)" },
//     { "value": "RON", "label": "Romanian Leu (RON)" },
//     { "value": "RSD", "label": "Serbian Dinar (RSD)" },
//     { "value": "RUB", "label": "Russian Ruble (RUB)" },
//     { "value": "RWF", "label": "Rwandan Franc (RWF)" },
//     { "value": "SAR", "label": "Saudi Riyal (SAR)" },
//     { "value": "SBD", "label": "Solomon Islands Dollar (SBD)" },
//     { "value": "SCR", "label": "Seychellois Rupee (SCR)" },
//     { "value": "SDG", "label": "Sudanese Pound (SDG)" },
//     { "value": "SEK", "label": "Swedish Krona (SEK)" },
//     { "value": "SGD", "label": "Singapore Dollar (SGD)" },
//     { "value": "SHP", "label": "Saint Helena Pound (SHP)" },
//     { "value": "SLL", "label": "Sierra Leonean Leone (SLL)" },
//     { "value": "SOS", "label": "Somali Shilling (SOS)" },
//     { "value": "SRD", "label": "Surinamese Dollar (SRD)" },
//     { "value": "STN", "label": "São Tomé and Príncipe Dobra (STN)" },
//     { "value": "SVC", "label": "Salvadoran Colón (SVC)" },
//     { "value": "SZL", "label": "Swazi Lilangeni (SZL)" },
//     { "value": "THB", "label": "Thai Baht (THB)" },
//     { "value": "TND", "label": "Tunisian Dinar (TND)" },
//     { "value": "TOP", "label": "Tongan Paʻanga (TOP)" },
//     { "value": "TRY", "label": "Turkish Lira (TRY)" },
//     { "value": "TTD", "label": "Trinidad and Tobago Dollar (TTD)" },
//     { "value": "TWD", "label": "New Taiwan Dollar (TWD)" },
//     { "value": "TZS", "label": "Tanzanian Shilling (TZS)" },
//     { "value": "UAH", "label": "Ukrainian Hryvnia (UAH)" },
//     { "value": "UGX", "label": "Ugandan Shilling (UGX)" },
//     { "value": "USD", "label": "United States Dollar (USD)" },
//     { "value": "UYU", "label": "Uruguayan Peso (UYU)" },
//     { "value": "UZS", "label": "Uzbekistani Som (UZS)" },
//     { "value": "VEF", "label": "Venezuelan Bolívar (VEF)" },
//     { "value": "VND", "label": "Vietnamese Dong (VND)" },
//     { "value": "VUV", "label": "Vanuatu Vatu (VUV)" },
//     { "value": "WST", "label": "Samoan Tala (WST)" },
//     { "value": "XAF", "label": "Central African CFA Franc (XAF)" },
//     { "value": "XCD", "label": "East Caribbean Dollar (XCD)" },
//     { "value": "XOF", "label": "West African CFA Franc (XOF)" },
//     { "value": "XPF", "label": "CFP Franc (XPF)" },
//     { "value": "YER", "label": "Yemeni Rial (YER)" },
//     { "value": "ZAR", "label": "South African Rand (ZAR)" },
//     { "value": "ZMW", "label": "Zambian Kwacha (ZMW)" },
//     { "value": "ZWL", "label": "Zimbabwean Dollar (ZWL)" }
// ]

export const CURRENCY = [
    { "value": "AFN", "label": "Afghan Afghani (AFN)", "timezone": "Asia/Kabul" },
    { "value": "USD", "label": "United States Dollar (USD)", "timezone": "America/New_York" },
    { "value": "EGP", "label": "Egyptian Pound (EGP)", "timezone": "Africa/Cairo" },
    { "value": "EUR", "label": "Euro (EUR)", "timezone": "Europe/Paris" },
    { "value": "INR", "label": "Indian Rupee (INR)", "timezone": "Asia/Kolkata" },
    { "value": "ARS", "label": "Argentine Peso (ARS)", "timezone": "America/Argentina/Buenos_Aires" },
    { "value": "AUD", "label": "Australian Dollar (AUD)", "timezone": "Australia/Sydney" },
    { "value": "CAD", "label": "Canadian Dollar (CAD)", "timezone": "America/Toronto" },
    { "value": "BHD", "label": "Bahraini Dinar (BHD)", "timezone": "Asia/Bahrain" },
    { "value": "BBD", "label": "Barbadian Dollar (BBD)", "timezone": "America/Barbados" },
    { "value": "BND", "label": "Brunei Dollar (BND)", "timezone": "Asia/Brunei" },
    { "value": "BGN", "label": "Bulgarian Lev (BGN)", "timezone": "Europe/Sofia" },
    { "value": "BRL", "label": "Brazilian Real (BRL)", "timezone": "America/Sao_Paulo" },
    { "value": "KHR", "label": "Cambodian Riel (KHR)", "timezone": "Asia/Phnom_Penh" },
    { "value": "CHF", "label": "Swiss Franc (CHF)", "timezone": "Europe/Zurich" },
    { "value": "CNY", "label": "Chinese Yuan (CNY)", "timezone": "Asia/Shanghai" },
    { "value": "COP", "label": "Colombian Peso (COP)", "timezone": "America/Bogota" },
    { "value": "HRK", "label": "Croatian Kuna (HRK)", "timezone": "Europe/Zagreb" },
    { "value": "CZK", "label": "Czech Koruna (CZK)", "timezone": "Europe/Prague" },
    { "value": "DKK", "label": "Danish Krone (DKK)", "timezone": "Europe/Copenhagen" },
    { "value": "DJF", "label": "Djiboutian Franc (DJF)", "timezone": "Africa/Djibouti" },
    { "value": "DOP", "label": "Dominican Peso (DOP)", "timezone": "America/Santo_Domingo" },
    { "value": "FJD", "label": "Fijian Dollar (FJD)", "timezone": "Pacific/Fiji" },
    { "value": "GEL", "label": "Georgian Lari (GEL)", "timezone": "Asia/Tbilisi" },
    { "value": "GHS", "label": "Ghanaian Cedi (GHS)", "timezone": "Africa/Accra" },
    { "value": "GIP", "label": "Gibraltar Pound (GIP)", "timezone": "Europe/Gibraltar" },
    { "value": "GNF", "label": "Guinean Franc (GNF)", "timezone": "Africa/Conakry" },
    { "value": "GYD", "label": "Guyanese Dollar (GYD)", "timezone": "America/Guyana" },
    { "value": "HKD", "label": "Hong Kong Dollar (HKD)", "timezone": "Asia/Hong_Kong" },
    { "value": "HNL", "label": "Honduran Lempira (HNL)", "timezone": "America/Tegucigalpa" },
    { "value": "HUF", "label": "Hungarian Forint (HUF)", "timezone": "Europe/Budapest" },
    { "value": "IDR", "label": "Indonesian Rupiah (IDR)", "timezone": "Asia/Jakarta" },
    { "value": "ISK", "label": "Icelandic Krona (ISK)", "timezone": "Atlantic/Reykjavik" },
    { "value": "IRR", "label": "Iranian Rial (IRR)", "timezone": "Asia/Tehran" },
    { "value": "IQD", "label": "Iraqi Dinar (IQD)", "timezone": "Asia/Baghdad" },
    { "value": "ILS", "label": "Israeli New Shekel (ILS)", "timezone": "Asia/Jerusalem" },
    { "value": "JMD", "label": "Jamaican Dollar (JMD)", "timezone": "America/Jamaica" },
    { "value": "JPY", "label": "Japanese Yen (JPY)", "timezone": "Asia/Tokyo" },
    { "value": "KES", "label": "Kenyan Shilling (KES)", "timezone": "Africa/Nairobi" },
    { "value": "KGS", "label": "Kyrgyzstani Som (KGS)", "timezone": "Asia/Bishkek" },
    { "value": "KMF", "label": "Comorian Franc (KMF)", "timezone": "Indian/Comoro" },
    { "value": "KRW", "label": "South Korean Won (KRW)", "timezone": "Asia/Seoul" },
    { "value": "KWD", "label": "Kuwaiti Dinar (KWD)", "timezone": "Asia/Kuwait" },
    { "value": "KYD", "label": "Cayman Islands Dollar (KYD)", "timezone": "America/Cayman" },
    { "value": "LAK", "label": "Lao Kip (LAK)", "timezone": "Asia/Vientiane" },
    { "value": "LBP", "label": "Lebanese Pound (LBP)", "timezone": "Asia/Beirut" },
    { "value": "LKR", "label": "Sri Lankan Rupee (LKR)", "timezone": "Asia/Colombo" },
    { "value": "LRD", "label": "Liberian Dollar (LRD)", "timezone": "Africa/Monrovia" },
    { "value": "LTL", "label": "Lithuanian Litas (LTL)", "timezone": "Europe/Vilnius" },
    { "value": "MAD", "label": "Moroccan Dirham (MAD)", "timezone": "Africa/Casablanca" },
    { "value": "MDL", "label": "Moldovan Leu (MDL)", "timezone": "Europe/Chisinau" },
    { "value": "MKD", "label": "Macedonian Denar (MKD)", "timezone": "Europe/Skopje" },
    { "value": "MMK", "label": "Myanmar Kyat (MMK)", "timezone": "Asia/Yangon" },
    { "value": "MNT", "label": "Mongolian Tugrik (MNT)", "timezone": "Asia/Ulaanbaatar" },
    { "value": "MOP", "label": "Macanese Pataca (MOP)", "timezone": "Asia/Macau" },
    { "value": "MUR", "label": "Mauritian Rupee (MUR)", "timezone": "Indian/Mauritius" },
    { "value": "MXN", "label": "Mexican Peso (MXN)", "timezone": "America/Mexico_City" },
    { "value": "MYR", "label": "Malaysian Ringgit (MYR)", "timezone": "Asia/Kuala_Lumpur" },
    { "value": "MZN", "label": "Mozambican Metical (MZN)", "timezone": "Africa/Maputo" },
    { "value": "NAD", "label": "Namibian Dollar (NAD)", "timezone": "Africa/Windhoek" },
    { "value": "NGN", "label": "Nigerian Naira (NGN)", "timezone": "Africa/Lagos" },
    { "value": "NIO", "label": "Nicaraguan Córdoba (NIO)", "timezone": "America/Managua" },
    { "value": "NOK", "label": "Norwegian Krone (NOK)", "timezone": "Europe/Oslo" },
    { "value": "NPR", "label": "Nepalese Rupee (NPR)", "timezone": "Asia/Kathmandu" },
    { "value": "OMR", "label": "Omani Rial (OMR)", "timezone": "Asia/Muscat" },
    { "value": "PAB", "label": "Panamanian Balboa (PAB)", "timezone": "America/Panama" },
    { "value": "PEN", "label": "Peruvian Nuevo Sol (PEN)", "timezone": "America/Lima" },
    { "value": "PGK", "label": "Papua New Guinean Kina (PGK)", "timezone": "Pacific/Port_Moresby" },
    { "value": "PHP", "label": "Philippine Peso (PHP)", "timezone": "Asia/Manila" },
    { "value": "PKR", "label": "Pakistani Rupee (PKR)", "timezone": "Asia/Karachi" },
    { "value": "PLN", "label": "Polish Zloty (PLN)", "timezone": "Europe/Warsaw" },
    { "value": "PYG", "label": "Paraguayan Guarani (PYG)", "timezone": "America/Asuncion" },
    { "value": "QAR", "label": "Qatari Rial (QAR)", "timezone": "Asia/Qatar" },
    { "value": "RON", "label": "Romanian Leu (RON)", "timezone": "Europe/Bucharest" },
    { "value": "RUB", "label": "Russian Ruble (RUB)", "timezone": "Europe/Moscow" },
    { "value": "RWF", "label": "Rwandan Franc (RWF)", "timezone": "Africa/Kigali" },
    { "value": "SAR", "label": "Saudi Riyal (SAR)", "timezone": "Asia/Riyadh" },
    { "value": "SBD", "label": "Solomon Islands Dollar (SBD)", "timezone": "Pacific/Honiara" },
    { "value": "SCR", "label": "Seychellois Rupee (SCR)", "timezone": "Indian/Mahe" },
    { "value": "SGD", "label": "Singapore Dollar (SGD)", "timezone": "Asia/Singapore" },
    { "value": "SHP", "label": "Saint Helena Pound (SHP)", "timezone": "Atlantic/St_Helena" },
    { "value": "SLL", "label": "Sierra Leonean Leone (SLL)", "timezone": "Africa/Freetown" },
    { "value": "SOS", "label": "Somali Shilling (SOS)", "timezone": "Africa/Mogadishu" },
    { "value": "SRD", "label": "Surinamese Dollar (SRD)", "timezone": "America/Paramaribo" },
    { "value": "SSP", "label": "South Sudanese Pound (SSP)", "timezone": "Africa/Juba" },
    { "value": "STN", "label": "São Tomé and Príncipe Dobra (STN)", "timezone": "Africa/Sao_Tome" },
    { "value": "SYP", "label": "Syrian Pound (SYP)", "timezone": "Asia/Damascus" },
    { "value": "SZL", "label": "Swazi Lilangeni (SZL)", "timezone": "Africa/Mbabane" },
    { "value": "THB", "label": "Thai Baht (THB)", "timezone": "Asia/Bangkok" },
    { "value": "TJS", "label": "Tajikistani Somoni (TJS)", "timezone": "Asia/Dushanbe" },
    { "value": "TMT", "label": "Turkmenistan Manat (TMT)", "timezone": "Asia/Ashgabat" },
    { "value": "TND", "label": "Tunisian Dinar (TND)", "timezone": "Africa/Tunis" },
    { "value": "TOP", "label": "Tongan Paʻanga (TOP)", "timezone": "Pacific/Tongatapu" },
    { "value": "TRY", "label": "Turkish Lira (TRY)", "timezone": "Europe/Istanbul" },
    { "value": "TTD", "label": "Trinidad and Tobago Dollar (TTD)", "timezone": "America/Port_of_Spain" },
    { "value": "TWD", "label": "New Taiwan Dollar (TWD)", "timezone": "Asia/Taipei" },
    { "value": "TZS", "label": "Tanzanian Shilling (TZS)", "timezone": "Africa/Dar_es_Salaam" },
    { "value": "UAH", "label": "Ukrainian Hryvnia (UAH)", "timezone": "Europe/Kiev" },
    { "value": "UGX", "label": "Ugandan Shilling (UGX)", "timezone": "Africa/Kampala" },
    { "value": "UYU", "label": "Uruguayan Peso (UYU)", "timezone": "America/Montevideo" },
    { "value": "UZS", "label": "Uzbekistani Som (UZS)", "timezone": "Asia/Tashkent" },
    { "value": "VES", "label": "Venezuelan Bolívar Soberano (VES)", "timezone": "America/Caracas" },
    { "value": "VND", "label": "Vietnamese Dong (VND)", "timezone": "Asia/Ho_Chi_Minh" },
    { "value": "VUV", "label": "Vanuatu Vatu (VUV)", "timezone": "Pacific/Efate" },
    { "value": "WST", "label": "Samoan Tala (WST)", "timezone": "Pacific/Apia" },
    { "value": "XAF", "label": "Central African CFA Franc (XAF)", "timezone": "Africa/Douala" },
    { "value": "XCD", "label": "East Caribbean Dollar (XCD)", "timezone": "America/Antigua" },
    { "value": "XOF", "label": "West African CFA Franc (XOF)", "timezone": "Africa/Abidjan" },
    { "value": "XPF", "label": "CFP Franc (XPF)", "timezone": "Pacific/Tahiti" },
    { "value": "YER", "label": "Yemeni Rial (YER)", "timezone": "Asia/Aden" },
    { "value": "ZAR", "label": "South African Rand (ZAR)", "timezone": "Africa/Johannesburg" },
    { "value": "ZMW", "label": "Zambian Kwacha (ZMW)", "timezone": "Africa/Lusaka" },
    { "value": "ZWL", "label": "Zimbabwean Dollar (ZWL)", "timezone": "Africa/Harare" }
];