// export const CURRENCY = [
//     { "value": "AED", "label": "United Arab Emirates Dirham (AED)" },
//     { "value": "AFN", "label": "Afghan Afghani (AFN)" },
//     { "value": "ALL", "label": "Albanian Lek (ALL)" },
//     { "value": "AMD", "label": "Armenian Dram (AMD)" },
//     { "value": "ANG", "label": "Netherlands Antillean Guilder (ANG)" },
//     { "value": "AOA", "label": "Angolan Kwanza (AOA)" },
//     { "value": "ARS", "label": "Argentine Peso (ARS)" },
//     { "value": "AUD", "label": "Australian Dollar (AUD)" },
//     { "value": "AWG", "label": "Aruban Florin (AWG)" },
//     { "value": "AZN", "label": "Azerbaijani Manat (AZN)" },
//     { "value": "BAM", "label": "Bosnia-Herzegovina Convertible Mark (BAM)" },
//     { "value": "BBD", "label": "Barbadian Dollar (BBD)" },
//     { "value": "BDT", "label": "Bangladeshi Taka (BDT)" },
//     { "value": "BGN", "label": "Bulgarian Lev (BGN)" },
//     { "value": "BHD", "label": "Bahraini Dinar (BHD)" },
//     { "value": "BIF", "label": "Burundian Franc (BIF)" },
//     { "value": "BMD", "label": "Bermudian Dollar (BMD)" },
//     { "value": "BND", "label": "Brunei Dollar (BND)" },
//     { "value": "BOB", "label": "Bolivian Boliviano (BOB)" },
//     { "value": "BRL", "label": "Brazilian Real (BRL)" },
//     { "value": "BSD", "label": "Bahamian Dollar (BSD)" },
//     { "value": "BTN", "label": "Bhutanese Ngultrum (BTN)" },
//     { "value": "BWP", "label": "Botswana Pula (BWP)" },
//     { "value": "BYN", "label": "Belarusian Ruble (BYN)" },
//     { "value": "BZD", "label": "Belize Dollar (BZD)" },
//     { "value": "CAD", "label": "Canadian Dollar (CAD)" },
//     { "value": "CDF", "label": "Congolese Franc (CDF)" },
//     { "value": "CHF", "label": "Swiss Franc (CHF)" },
//     { "value": "CLP", "label": "Chilean Peso (CLP)" },
//     { "value": "CNY", "label": "Chinese Yuan (CNY)" },
//     { "value": "COP", "label": "Colombian Peso (COP)" },
//     { "value": "CRC", "label": "Costa Rican Colón (CRC)" },
//     { "value": "CUC", "label": "Cuban Convertible Peso (CUC)" },
//     { "value": "CUP", "label": "Cuban Peso (CUP)" },
//     { "value": "CVE", "label": "Cape Verdean Escudo (CVE)" },
//     { "value": "CZK", "label": "Czech Koruna (CZK)" },
//     { "value": "DJF", "label": "Djiboutian Franc (DJF)" },
//     { "value": "DKK", "label": "Danish Krone (DKK)" },
//     { "value": "DOP", "label": "Dominican Peso (DOP)" },
//     { "value": "DZD", "label": "Algerian Dinar (DZD)" },
//     { "value": "EGP", "label": "Egyptian Pound (EGP)" },
//     { "value": "ERN", "label": "Eritrean Nakfa (ERN)" },
//     { "value": "ETB", "label": "Ethiopian Birr (ETB)" },
//     { "value": "EUR", "label": "Euro (EUR)" },
//     { "value": "FJD", "label": "Fijian Dollar (FJD)" },
//     { "value": "FKP", "label": "Falkland Islands Pound (FKP)" },
//     { "value": "GBP", "label": "British Pound Sterling (GBP)" },
//     { "value": "GEL", "label": "Georgian Lari (GEL)" },
//     { "value": "GHS", "label": "Ghanaian Cedi (GHS)" },
//     { "value": "GIP", "label": "Gibraltar Pound (GIP)" },
//     { "value": "GMD", "label": "Gambian Dalasi (GMD)" },
//     { "value": "GNF", "label": "Guinean Franc (GNF)" },
//     { "value": "GTQ", "label": "Guatemalan Quetzal (GTQ)" },
//     { "value": "GYD", "label": "Guyanese Dollar (GYD)" },
//     { "value": "HKD", "label": "Hong Kong Dollar (HKD)" },
//     { "value": "HNL", "label": "Honduran Lempira (HNL)" },
//     { "value": "HRK", "label": "Croatian Kuna (HRK)" },
//     { "value": "HTG", "label": "Haitian Gourde (HTG)" },
//     { "value": "HUF", "label": "Hungarian Forint (HUF)" },
//     { "value": "IDR", "label": "Indonesian Rupiah (IDR)" },
//     { "value": "ILS", "label": "Israeli New Shekel (ILS)" },
//     { "value": "INR", "label": "Indian Rupee (INR)" },
//     { "value": "IQD", "label": "Iraqi Dinar (IQD)" },
//     { "value": "IRR", "label": "Iranian Rial (IRR)" },
//     { "value": "ISK", "label": "Icelandic Króna (ISK)" },
//     { "value": "JMD", "label": "Jamaican Dollar (JMD)" },
//     { "value": "JOD", "label": "Jordanian Dinar (JOD)" },
//     { "value": "JPY", "label": "Japanese Yen (JPY)" },
//     { "value": "KES", "label": "Kenyan Shilling (KES)" },
//     { "value": "KGS", "label": "Kyrgyzstani Som (KGS)" },
//     { "value": "KHR", "label": "Cambodian Riel (KHR)" },
//     { "value": "KMF", "label": "Comorian Franc (KMF)" },
//     { "value": "KRW", "label": "South Korean Won (KRW)" },
//     { "value": "KWD", "label": "Kuwaiti Dinar (KWD)" },
//     { "value": "KYD", "label": "Cayman Islands Dollar (KYD)" },
//     { "value": "KZT", "label": "Kazakhstani Tenge (KZT)" },
//     { "value": "LAK", "label": "Lao Kip (LAK)" },
//     { "value": "LBP", "label": "Lebanese Pound (LBP)" },
//     { "value": "LKR", "label": "Sri Lankan Rupee (LKR)" },
//     { "value": "LRD", "label": "Liberian Dollar (LRD)" },
//     { "value": "LSL", "label": "Lesotho Loti (LSL)" },
//     { "value": "LYD", "label": "Libyan Dinar (LYD)" },
//     { "value": "MAD", "label": "Moroccan Dirham (MAD)" },
//     { "value": "MDL", "label": "Moldovan Leu (MDL)" },
//     { "value": "MKD", "label": "Macedonian Denar (MKD)" },
//     { "value": "MMK", "label": "Myanmar Kyat (MMK)" },
//     { "value": "MNT", "label": "Mongolian Tögrög (MNT)" },
//     { "value": "MOP", "label": "Macanese Pataca (MOP)" },
//     { "value": "MRU", "label": "Mauritanian Ouguiya (MRU)" },
//     { "value": "MUR", "label": "Mauritian Rupee (MUR)" },
//     { "value": "MVR", "label": "Maldivian Rufiyaa (MVR)" },
//     { "value": "MWK", "label": "Malawian Kwacha (MWK)" },
//     { "value": "MXN", "label": "Mexican Peso (MXN)" },
//     { "value": "MYR", "label": "Malaysian Ringgit (MYR)" },
//     { "value": "MZN", "label": "Mozambican Metical (MZN)" },
//     { "value": "NAD", "label": "Namibian Dollar (NAD)" },
//     { "value": "NGN", "label": "Nigerian Naira (NGN)" },
//     { "value": "NIO", "label": "Nicaraguan Córdoba (NIO)" },
//     { "value": "NOK", "label": "Norwegian Krone (NOK)" },
//     { "value": "NPR", "label": "Nepalese Rupee (NPR)" },
//     { "value": "NZD", "label": "New Zealand Dollar (NZD)" },
//     { "value": "OMR", "label": "Omani Rial (OMR)" },
//     { "value": "PAB", "label": "Panamanian Balboa (PAB)" },
//     { "value": "PEN", "label": "Peruvian Sol (PEN)" },
//     { "value": "PGK", "label": "Papua New Guinean Kina (PGK)" },
//     { "value": "PHP", "label": "Philippine Peso (PHP)" },
//     { "value": "PKR", "label": "Pakistani Rupee (PKR)" },
//     { "value": "PLN", "label": "Polish Złoty (PLN)" },
//     { "value": "PYG", "label": "Paraguayan Guaraní (PYG)" },
//     { "value": "QAR", "label": "Qatari Riyal (QAR)" },
//     { "value": "RON", "label": "Romanian Leu (RON)" },
//     { "value": "RSD", "label": "Serbian Dinar (RSD)" },
//     { "value": "RUB", "label": "Russian Ruble (RUB)" },
//     { "value": "RWF", "label": "Rwandan Franc (RWF)" },
//     { "value": "SAR", "label": "Saudi Riyal (SAR)" },
//     { "value": "SBD", "label": "Solomon Islands Dollar (SBD)" },
//     { "value": "SCR", "label": "Seychellois Rupee (SCR)" },
//     { "value": "SDG", "label": "Sudanese Pound (SDG)" },
//     { "value": "SEK", "label": "Swedish Krona (SEK)" },
//     { "value": "SGD", "label": "Singapore Dollar (SGD)" },
//     { "value": "SHP", "label": "Saint Helena Pound (SHP)" },
//     { "value": "SLL", "label": "Sierra Leonean Leone (SLL)" },
//     { "value": "SOS", "label": "Somali Shilling (SOS)" },
//     { "value": "SRD", "label": "Surinamese Dollar (SRD)" },
//     { "value": "STN", "label": "São Tomé and Príncipe Dobra (STN)" },
//     { "value": "SVC", "label": "Salvadoran Colón (SVC)" },
//     { "value": "SZL", "label": "Swazi Lilangeni (SZL)" },
//     { "value": "THB", "label": "Thai Baht (THB)" },
//     { "value": "TND", "label": "Tunisian Dinar (TND)" },
//     { "value": "TOP", "label": "Tongan Paʻanga (TOP)" },
//     { "value": "TRY", "label": "Turkish Lira (TRY)" },
//     { "value": "TTD", "label": "Trinidad and Tobago Dollar (TTD)" },
//     { "value": "TWD", "label": "New Taiwan Dollar (TWD)" },
//     { "value": "TZS", "label": "Tanzanian Shilling (TZS)" },
//     { "value": "UAH", "label": "Ukrainian Hryvnia (UAH)" },
//     { "value": "UGX", "label": "Ugandan Shilling (UGX)" },
//     { "value": "USD", "label": "United States Dollar (USD)" },
//     { "value": "UYU", "label": "Uruguayan Peso (UYU)" },
//     { "value": "UZS", "label": "Uzbekistani Som (UZS)" },
//     { "value": "VEF", "label": "Venezuelan Bolívar (VEF)" },
//     { "value": "VND", "label": "Vietnamese Dong (VND)" },
//     { "value": "VUV", "label": "Vanuatu Vatu (VUV)" },
//     { "value": "WST", "label": "Samoan Tala (WST)" },
//     { "value": "XAF", "label": "Central African CFA Franc (XAF)" },
//     { "value": "XCD", "label": "East Caribbean Dollar (XCD)" },
//     { "value": "XOF", "label": "West African CFA Franc (XOF)" },
//     { "value": "XPF", "label": "CFP Franc (XPF)" },
//     { "value": "YER", "label": "Yemeni Rial (YER)" },
//     { "value": "ZAR", "label": "South African Rand (ZAR)" },
//     { "value": "ZMW", "label": "Zambian Kwacha (ZMW)" },
//     { "value": "ZWL", "label": "Zimbabwean Dollar (ZWL)" }
// ]

export const CURRENCY =
    [
        { "value": "AFN", "label": "Afghan Afghani (AFN)", "timezone": "Asia/Kabul", "utc_offset": "+04:30", "actual_time": "2025-12-02 16:00:00" },
        { "value": "USD", "label": "United States Dollar (USD)", "timezone": "America/New_York", "utc_offset": "-05:00", "actual_time": "2025-12-02 02:30:00" },
        { "value": "EGP", "label": "Egyptian Pound (EGP)", "timezone": "Africa/Cairo", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "EUR", "label": "Euro (EUR)", "timezone": "Europe/Paris", "utc_offset": "+01:00", "actual_time": "2025-12-02 07:00:00" },
        { "value": "INR", "label": "Indian Rupee (INR)", "timezone": "Asia/Kolkata", "utc_offset": "+05:30", "actual_time": "2025-12-02 17:30:00" },
        { "value": "ARS", "label": "Argentine Peso (ARS)", "timezone": "America/Argentina/Buenos_Aires", "utc_offset": "-03:00", "actual_time": "2025-12-02 03:30:00" },
        { "value": "AUD", "label": "Australian Dollar (AUD)", "timezone": "Australia/Sydney", "utc_offset": "+10:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "CAD", "label": "Canadian Dollar (CAD)", "timezone": "America/Toronto", "utc_offset": "-05:00", "actual_time": "2025-12-02 02:30:00" },
        { "value": "BHD", "label": "Bahraini Dinar (BHD)", "timezone": "Asia/Bahrain", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:00:00" },
        { "value": "BBD", "label": "Barbadian Dollar (BBD)", "timezone": "America/Barbados", "utc_offset": "-04:00", "actual_time": "2025-12-02 04:30:00" },
        { "value": "BND", "label": "Brunei Dollar (BND)", "timezone": "Asia/Brunei", "utc_offset": "+08:00", "actual_time": "2025-12-02 23:00:00" },
        { "value": "BGN", "label": "Bulgarian Lev (BGN)", "timezone": "Europe/Sofia", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "BRL", "label": "Brazilian Real (BRL)", "timezone": "America/Sao_Paulo", "utc_offset": "-03:00", "actual_time": "2025-12-02 03:30:00" },
        { "value": "KHR", "label": "Cambodian Riel (KHR)", "timezone": "Asia/Phnom_Penh", "utc_offset": "+07:00", "actual_time": "2025-12-02 21:00:00" },
        { "value": "CHF", "label": "Swiss Franc (CHF)", "timezone": "Europe/Zurich", "utc_offset": "+01:00", "actual_time": "2025-12-02 07:00:00" },
        { "value": "CNY", "label": "Chinese Yuan (CNY)", "timezone": "Asia/Shanghai", "utc_offset": "+08:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "COP", "label": "Colombian Peso (COP)", "timezone": "America/Bogota", "utc_offset": "-05:00", "actual_time": "2025-12-02 02:30:00" },
        { "value": "HRK", "label": "Croatian Kuna (HRK)", "timezone": "Europe/Zagreb", "utc_offset": "+01:00", "actual_time": "2025-12-02 07:00:00" },
        { "value": "CYP", "label": "Cypriot Pound (CYP)", "timezone": "Asia/Nicosia", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "CZE", "label": "Czech Koruna (CZE)", "timezone": "Europe/Prague", "utc_offset": "+01:00", "actual_time": "2025-12-02 07:00:00" },
        { "value": "DKK", "label": "Danish Krone (DKK)", "timezone": "Europe/Copenhagen", "utc_offset": "+01:00", "actual_time": "2025-12-02 07:00:00" },
        { "value": "DJF", "label": "Djiboutian Franc (DJF)", "timezone": "Africa/Djibouti", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "DOM", "label": "Dominican Peso (DOM)", "timezone": "America/Santo_Domingo", "utc_offset": "-04:00", "actual_time": "2025-12-02 04:30:00" },
        { "value": "EGP", "label": "Egyptian Pound (EGP)", "timezone": "Africa/Cairo", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "FJD", "label": "Fijian Dollar (FJD)", "timezone": "Pacific/Fiji", "utc_offset": "+12:00", "actual_time": "2025-12-02 23:00:00" },
        { "value": "HRK", "label": "Croatian Kuna (HRK)", "timezone": "Europe/Zagreb", "utc_offset": "+01:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "CYP", "label": "Cypriot Pound (CYP)", "timezone": "Asia/Nicosia", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "CZE", "label": "Czech Koruna (CZE)", "timezone": "Europe/Prague", "utc_offset": "+01:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "DKK", "label": "Danish Krone (DKK)", "timezone": "Europe/Copenhagen", "utc_offset": "+01:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "DJF", "label": "Djiboutian Franc (DJF)", "timezone": "Africa/Djibouti", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "DOM", "label": "Dominican Peso (DOM)", "timezone": "America/Santo_Domingo", "utc_offset": "-04:00", "actual_time": "2025-12-02 04:30:00" },
        { "value": "EGP", "label": "Egyptian Pound (EGP)", "timezone": "Africa/Cairo", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "FJD", "label": "Fijian Dollar (FJD)", "timezone": "Pacific/Fiji", "utc_offset": "+12:00", "actual_time": "2025-12-02 23:00:00" },
        { "value": "FOK", "label": "Faroese Króna (FOK)", "timezone": "Atlantic/Faroe", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "FIN", "label": "Finnish Markka (FIN)", "timezone": "Europe/Helsinki", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "GMD", "label": "Gambian Dalasi (GMD)", "timezone": "Africa/Banjul", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "GEL", "label": "Georgian Lari (GEL)", "timezone": "Asia/Tbilisi", "utc_offset": "+04:00", "actual_time": "2025-12-02 19:30:00" },
        { "value": "GHS", "label": "Ghanaian Cedi (GHS)", "timezone": "Africa/Accra", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "GIP", "label": "Gibraltar Pound (GIP)", "timezone": "Europe/Gibraltar", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "GMD", "label": "Gambian Dalasi (GMD)", "timezone": "Africa/Banjul", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "GNF", "label": "Guinean Franc (GNF)", "timezone": "Africa/Conakry", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "GUY", "label": "Guyanese Dollar (GUY)", "timezone": "America/Guyana", "utc_offset": "-04:00", "actual_time": "2025-12-02 04:30:00" },
        { "value": "HKD", "label": "Hong Kong Dollar (HKD)", "timezone": "Asia/Hong_Kong", "utc_offset": "+08:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "HNL", "label": "Honduran Lempira (HNL)", "timezone": "America/Tegucigalpa", "utc_offset": "-06:00", "actual_time": "2025-12-02 01:30:00" },
        { "value": "HUF", "label": "Hungarian Forint (HUF)", "timezone": "Europe/Budapest", "utc_offset": "+01:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "IDR", "label": "Indonesian Rupiah (IDR)", "timezone": "Asia/Jakarta", "utc_offset": "+07:00", "actual_time": "2025-12-02 21:00:00" },
        { "value": "ISK", "label": "Icelandic Krona (ISK)", "timezone": "Atlantic/Reykjavik", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "INR", "label": "Indian Rupee (INR)", "timezone": "Asia/Kolkata", "utc_offset": "+05:30", "actual_time": "2025-12-02 17:30:00" },
        { "value": "IRR", "label": "Iranian Rial (IRR)", "timezone": "Asia/Tehran", "utc_offset": "+03:30", "actual_time": "2025-12-02 18:00:00" },
        { "value": "IQD", "label": "Iraqi Dinar (IQD)", "timezone": "Asia/Baghdad", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "ILS", "label": "Israeli New Shekel (ILS)", "timezone": "Asia/Jerusalem", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "JMD", "label": "Jamaican Dollar (JMD)", "timezone": "America/Jamaica", "utc_offset": "-05:00", "actual_time": "2025-12-02 02:30:00" },
        { "value": "JPY", "label": "Japanese Yen (JPY)", "timezone": "Asia/Tokyo", "utc_offset": "+09:00", "actual_time": "2025-12-02 23:30:00" },
        { "value": "KES", "label": "Kenyan Shilling (KES)", "timezone": "Africa/Nairobi", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:00:00" },
        { "value": "KGS", "label": "Kyrgyzstani Som (KGS)", "timezone": "Asia/Bishkek", "utc_offset": "+06:00", "actual_time": "2025-12-02 21:30:00" },
        { "value": "KHR", "label": "Cambodian Riel (KHR)", "timezone": "Asia/Phnom_Penh", "utc_offset": "+07:00", "actual_time": "2025-12-02 21:00:00" },
        { "value": "KMF", "label": "Comorian Franc (KMF)", "timezone": "Indian/Comoro", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "KRW", "label": "South Korean Won (KRW)", "timezone": "Asia/Seoul", "utc_offset": "+09:00", "actual_time": "2025-12-02 23:30:00" },
        { "value": "KWD", "label": "Kuwaiti Dinar (KWD)", "timezone": "Asia/Kuwait", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "KYD", "label": "Cayman Islands Dollar (KYD)", "timezone": "America/Cayman", "utc_offset": "-05:00", "actual_time": "2025-12-02 02:30:00" },
        { "value": "LAK", "label": "Lao Kip (LAK)", "timezone": "Asia/Vientiane", "utc_offset": "+07:00", "actual_time": "2025-12-02 21:00:00" },
        { "value": "LBP", "label": "Lebanese Pound (LBP)", "timezone": "Asia/Beirut", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "LSL", "label": "Lesotho Loti (LSL)", "timezone": "Africa/Maseru", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "LKR", "label": "Sri Lankan Rupee (LKR)", "timezone": "Asia/Colombo", "utc_offset": "+05:30", "actual_time": "2025-12-02 17:30:00" },
        { "value": "LRD", "label": "Liberian Dollar (LRD)", "timezone": "Africa/Monrovia", "utc_offset": "-00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "LSL", "label": "Lesotho Loti (LSL)", "timezone": "Africa/Maseru", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "LTL", "label": "Lithuanian Litas (LTL)", "timezone": "Europe/Vilnius", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "LUX", "label": "Luxembourg Franc (LUX)", "timezone": "Europe/Luxembourg", "utc_offset": "+01:00", "actual_time": "2025-12-02 07:00:00" },
        { "value": "MAD", "label": "Moroccan Dirham (MAD)", "timezone": "Africa/Casablanca", "utc_offset": "+01:00", "actual_time": "2025-12-02 07:00:00" },
        { "value": "MDL", "label": "Moldovan Leu (MDL)", "timezone": "Europe/Chisinau", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "MKD", "label": "Macedonian Denar (MKD)", "timezone": "Europe/Skopje", "utc_offset": "+01:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "MMK", "label": "Myanmar Kyat (MMK)", "timezone": "Asia/Yangon", "utc_offset": "+06:30", "actual_time": "2025-12-02 20:00:00" },
        { "value": "MNT", "label": "Mongolian Tugrik (MNT)", "timezone": "Asia/Ulaanbaatar", "utc_offset": "+08:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "MOP", "label": "Macanese Pataca (MOP)", "timezone": "Asia/Macau", "utc_offset": "+08:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "MUR", "label": "Mauritian Rupee (MUR)", "timezone": "Indian/Mauritius", "utc_offset": "+04:00", "actual_time": "2025-12-02 19:00:00" },
        { "value": "MXN", "label": "Mexican Peso (MXN)", "timezone": "America/Mexico_City", "utc_offset": "-06:00", "actual_time": "2025-12-02 01:30:00" },
        { "value": "MYR", "label": "Malaysian Ringgit (MYR)", "timezone": "Asia/Kuala_Lumpur", "utc_offset": "+08:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "MZN", "label": "Mozambican Metical (MZN)", "timezone": "Africa/Maputo", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "NAD", "label": "Namibian Dollar (NAD)", "timezone": "Africa/Windhoek", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "NGN", "label": "Nigerian Naira (NGN)", "timezone": "Africa/Lagos", "utc_offset": "+01:00", "actual_time": "2025-12-02 07:00:00" },
        { "value": "NIO", "label": "Nicaraguan Córdoba (NIO)", "timezone": "America/Managua", "utc_offset": "-06:00", "actual_time": "2025-12-02 01:30:00" },
        { "value": "NOK", "label": "Norwegian Krone (NOK)", "timezone": "Europe/Oslo", "utc_offset": "+01:00", "actual_time": "2025-12-02 07:00:00" },
        { "value": "NPR", "label": "Nepalese Rupee (NPR)", "timezone": "Asia/Kathmandu", "utc_offset": "+05:45", "actual_time": "2025-12-02 17:15:00" },
        { "value": "OMR", "label": "Omani Rial (OMR)", "timezone": "Asia/Muscat", "utc_offset": "+04:00", "actual_time": "2025-12-02 19:00:00" },
        { "value": "PAB", "label": "Panamanian Balboa (PAB)", "timezone": "America/Panama", "utc_offset": "-05:00", "actual_time": "2025-12-02 02:30:00" },
        { "value": "PEN", "label": "Peruvian Nuevo Sol (PEN)", "timezone": "America/Lima", "utc_offset": "-05:00", "actual_time": "2025-12-02 02:30:00" },
        { "value": "PGK", "label": "Papua New Guinean Kina (PGK)", "timezone": "Pacific/Port_Moresby", "utc_offset": "+10:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "PHP", "label": "Philippine Peso (PHP)", "timezone": "Asia/Manila", "utc_offset": "+08:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "PKR", "label": "Pakistani Rupee (PKR)", "timezone": "Asia/Karachi", "utc_offset": "+05:00", "actual_time": "2025-12-02 17:00:00" },
        { "value": "PLN", "label": "Polish Zloty (PLN)", "timezone": "Europe/Warsaw", "utc_offset": "+01:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "PYG", "label": "Paraguayan Guarani (PYG)", "timezone": "America/Asuncion", "utc_offset": "-04:00", "actual_time": "2025-12-02 04:30:00" },
        { "value": "QAR", "label": "Qatari Rial (QAR)", "timezone": "Asia/Qatar", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "RON", "label": "Romanian Leu (RON)", "timezone": "Europe/Bucharest", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "RUB", "label": "Russian Ruble (RUB)", "timezone": "Europe/Moscow", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "RWF", "label": "Rwandan Franc (RWF)", "timezone": "Africa/Kigali", "utc_offset": "+02:00", "actual_time": "2025-12-02 09:00:00" },
        { "value": "SAR", "label": "Saudi Riyal (SAR)", "timezone": "Asia/Riyadh", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "SBD", "label": "Solomon Islands Dollar (SBD)", "timezone": "Pacific/Honiara", "utc_offset": "+11:00", "actual_time": "2025-12-02 23:30:00" },
        { "value": "SCR", "label": "Seychellois Rupee (SCR)", "timezone": "Indian/Mahe", "utc_offset": "+04:00", "actual_time": "2025-12-02 19:00:00" },
        { "value": "SGD", "label": "Singapore Dollar (SGD)", "timezone": "Asia/Singapore", "utc_offset": "+08:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "SHP", "label": "Saint Helena Pound (SHP)", "timezone": "Atlantic/St_Helena", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "SLL", "label": "Sierra Leonean Leone (SLL)", "timezone": "Africa/Freetown", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "SOS", "label": "Somali Shilling (SOS)", "timezone": "Africa/Mogadishu", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "SRD", "label": "Surinamese Dollar (SRD)", "timezone": "America/Paramaribo", "utc_offset": "-03:00", "actual_time": "2025-12-02 03:30:00" },
        { "value": "SSP", "label": "South Sudanese Pound (SSP)", "timezone": "Africa/Juba", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "STN", "label": "São Tomé and Príncipe Dobra (STN)", "timezone": "Africa/Sao_Tome", "utc_offset": "+00:00", "actual_time": "2025-12-02 06:00:00" },
        { "value": "SUR", "label": "Surinamese Dollar (SUR)", "timezone": "America/Paramaribo", "utc_offset": "-03:00", "actual_time": "2025-12-02 03:30:00" },
        { "value": "SYP", "label": "Syrian Pound (SYP)", "timezone": "Asia/Damascus", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "SZL", "label": "Swazi Lilangeni (SZL)", "timezone": "Africa/Mbabane", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "THB", "label": "Thai Baht (THB)", "timezone": "Asia/Bangkok", "utc_offset": "+07:00", "actual_time": "2025-12-02 21:00:00" },
        { "value": "TJS", "label": "Tajikistani Somoni (TJS)", "timezone": "Asia/Dushanbe", "utc_offset": "+05:00", "actual_time": "2025-12-02 17:00:00" },
        { "value": "TMT", "label": "Turkmenistan Manat (TMT)", "timezone": "Asia/Ashgabat", "utc_offset": "+05:00", "actual_time": "2025-12-02 17:00:00" },
        { "value": "TND", "label": "Tunisian Dinar (TND)", "timezone": "Africa/Tunis", "utc_offset": "+01:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "TOP", "label": "Tongan Paʻanga (TOP)", "timezone": "Pacific/Tongatapu", "utc_offset": "+13:00", "actual_time": "2025-12-02 23:30:00" },
        { "value": "TRY", "label": "Turkish Lira (TRY)", "timezone": "Europe/Istanbul", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "TTD", "label": "Trinidad and Tobago Dollar (TTD)", "timezone": "America/Port_of_Spain", "utc_offset": "-04:00", "actual_time": "2025-12-02 04:30:00" },
        { "value": "TWD", "label": "New Taiwan Dollar (TWD)", "timezone": "Asia/Taipei", "utc_offset": "+08:00", "actual_time": "2025-12-02 22:00:00" },
        { "value": "TZS", "label": "Tanzanian Shilling (TZS)", "timezone": "Africa/Dar_es_Salaam", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "UAH", "label": "Ukrainian Hryvnia (UAH)", "timezone": "Europe/Kiev", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "UGX", "label": "Ugandan Shilling (UGX)", "timezone": "Africa/Kampala", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "UYU", "label": "Uruguayan Peso (UYU)", "timezone": "America/Montevideo", "utc_offset": "-03:00", "actual_time": "2025-12-02 03:30:00" },
        { "value": "UZS", "label": "Uzbekistani Som (UZS)", "timezone": "Asia/Tashkent", "utc_offset": "+05:00", "actual_time": "2025-12-02 17:00:00" },
        { "value": "VEF", "label": "Venezuelan Bolívar (VEF)", "timezone": "America/Caracas", "utc_offset": "-04:00", "actual_time": "2025-12-02 04:30:00" },
        { "value": "VND", "label": "Vietnamese Dong (VND)", "timezone": "Asia/Ho_Chi_Minh", "utc_offset": "+07:00", "actual_time": "2025-12-02 21:00:00" },
        { "value": "VUV", "label": "Vanuatu Vatu (VUV)", "timezone": "Pacific/Efate", "utc_offset": "+11:00", "actual_time": "2025-12-02 23:30:00" },
        { "value": "WST", "label": "Samoan Tala (WST)", "timezone": "Pacific/Apia", "utc_offset": "+13:00", "actual_time": "2025-12-02 23:30:00" },
        { "value": "YER", "label": "Yemeni Rial (YER)", "timezone": "Asia/Aden", "utc_offset": "+03:00", "actual_time": "2025-12-02 18:30:00" },
        { "value": "ZAR", "label": "South African Rand (ZAR)", "timezone": "Africa/Johannesburg", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "ZMW", "label": "Zambian Kwacha (ZMW)", "timezone": "Africa/Lusaka", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" },
        { "value": "ZWL", "label": "Zimbabwean Dollar (ZWL)", "timezone": "Africa/Harare", "utc_offset": "+02:00", "actual_time": "2025-12-02 08:00:00" }


    ]


