const VIEW_LEAD = 'VIEW_LEAD';
const EDIT_LEAD = 'EDIT_LEAD';
const DELETE_LEAD = 'DELETE_LEAD';
const VIEW_CONTACT = 'VIEW_CONTACT';
const EDIT_CONTACT = 'EDIT_CONTACT';
const DELETE_CONTACT = 'DELETE_CONTACT';

const VIEW_ACCOUNT = 'VIEW_ACCOUNT';
const EDIT_ACCOUNT = 'EDIT_ACCOUNT';
const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
const VIEW_PRODUCT = 'VIEW_PRODUCT';
const EDIT_PRODUCT = 'EDIT_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const MODIFY_ALL = 'MODIFY_ALL';
const VIEW_ALL = 'VIEW_ALL';
const LIST_ATTENDANCE = 'LIST_ATTENDANCE';

const VIEW_ATTENDANCE = 'VIEW_ATTENDANCE';


const VIEW_PURCHASE = 'VIEW_PURCHASE';
const MANAGE_PURCHASE = 'MANAGE_PURCHASE';
const VIEW_VENDOR = 'VIEW_VENDOR';
const MANAGE_VENDOR = 'MANAGE_VENDOR';
const REQUEST_BOOK = 'REQUEST_BOOK';
const MANAGE_BOOK_REQUESTS = 'MANAGE_BOOK_REQUESTS';
const VIEW_INVENTORY = 'VIEW_INVENTORY';
const MANAGE_INVENTORY = 'MANAGE_INVENTORY';
const VIEW_BOOK_ISSUE = 'VIEW_BOOK_ISSUE';
const MANAGE_BOOK_ISSUE = 'MANAGE_BOOK_ISSUE';


module.exports = {
    VIEW_LEAD, EDIT_LEAD, DELETE_LEAD,
    VIEW_CONTACT, EDIT_CONTACT, DELETE_CONTACT,
    VIEW_ACCOUNT, EDIT_ACCOUNT, DELETE_ACCOUNT,
    VIEW_PRODUCT, EDIT_PRODUCT, DELETE_PRODUCT,
    VIEW_ATTENDANCE, LIST_ATTENDANCE,
    MODIFY_ALL, VIEW_ALL,

    VIEW_PURCHASE, MANAGE_PURCHASE,
    VIEW_VENDOR, MANAGE_VENDOR,
    REQUEST_BOOK, MANAGE_BOOK_REQUESTS,
    VIEW_INVENTORY, MANAGE_INVENTORY,
    VIEW_BOOK_ISSUE, MANAGE_BOOK_ISSUE

};