// ================== COMMON ==================
const MODIFY_ALL = 'MODIFY_ALL';
const VIEW_ALL = 'VIEW_ALL';

// ================== DASHBOARD ==================
const VIEW_DASHBOARD = 'VIEW_DASHBOARD';

// ================== USERS ==================
const VIEW_USER = 'VIEW_USER';
const CREATE_USER = 'CREATE_USER';
const EDIT_USER = 'EDIT_USER';
const DELETE_USER = 'DELETE_USER';

// ================== USER ROLES ==================
const VIEW_USER_ROLE = 'VIEW_USER_ROLE';
const CREATE_USER_ROLE = 'CREATE_USER_ROLE';
const EDIT_USER_ROLE = 'EDIT_USER_ROLE';
const DELETE_USER_ROLE = 'DELETE_USER_ROLE';
const ASSIGN_PERMISSION = 'ASSIGN_PERMISSION';

// ================== COMPANY ==================
const VIEW_COMPANY = 'VIEW_COMPANY';
const EDIT_COMPANY = 'EDIT_COMPANY';

// ================== BOOKS ==================
const VIEW_BOOK = 'VIEW_BOOK';
const CREATE_BOOK = 'CREATE_BOOK';
const EDIT_BOOK = 'EDIT_BOOK';
const DELETE_BOOK = 'DELETE_BOOK';

// ================== AUTHORS ==================
const VIEW_AUTHOR = 'VIEW_AUTHOR';
const CREATE_AUTHOR = 'CREATE_AUTHOR';
const EDIT_AUTHOR = 'EDIT_AUTHOR';
const DELETE_AUTHOR = 'DELETE_AUTHOR';

// ================== CATEGORIES ==================
const VIEW_CATEGORY = 'VIEW_CATEGORY';
const CREATE_CATEGORY = 'CREATE_CATEGORY';
const EDIT_CATEGORY = 'EDIT_CATEGORY';
const DELETE_CATEGORY = 'DELETE_CATEGORY';

// ================== VENDORS ==================
const VIEW_VENDOR = 'VIEW_VENDOR';
const MANAGE_VENDOR = 'MANAGE_VENDOR';

// ================== PURCHASE ==================
const VIEW_PURCHASE = 'VIEW_PURCHASE';
const MANAGE_PURCHASE = 'MANAGE_PURCHASE';

// ================== INVENTORY ==================
const VIEW_INVENTORY = 'VIEW_INVENTORY';
const MANAGE_INVENTORY = 'MANAGE_INVENTORY';

// ================== BOOK ISSUE ==================
const VIEW_BOOK_ISSUE = 'VIEW_BOOK_ISSUE';
const MANAGE_BOOK_ISSUE = 'MANAGE_BOOK_ISSUE';

// ================== BOOK REQUEST ==================
const REQUEST_BOOK = 'REQUEST_BOOK';
const MANAGE_BOOK_REQUESTS = 'MANAGE_BOOK_REQUESTS';

// ================== BOOK SUBMISSION ==================
const VIEW_BOOK_SUBMISSION = 'VIEW_BOOK_SUBMISSION';
const APPROVE_BOOK_SUBMISSION = 'APPROVE_BOOK_SUBMISSION';
const REJECT_BOOK_SUBMISSION = 'REJECT_BOOK_SUBMISSION';

// ================== LIBRARY MEMBER ==================
const VIEW_LIBRARY_MEMBER = 'VIEW_LIBRARY_MEMBER';
const CREATE_LIBRARY_MEMBER = 'CREATE_LIBRARY_MEMBER';
const EDIT_LIBRARY_MEMBER = 'EDIT_LIBRARY_MEMBER';
const DELETE_LIBRARY_MEMBER = 'DELETE_LIBRARY_MEMBER';

// ================== PUBLISHER ==================
const VIEW_PUBLISHER = 'VIEW_PUBLISHER';
const CREATE_PUBLISHER = 'CREATE_PUBLISHER';
const EDIT_PUBLISHER = 'EDIT_PUBLISHER';
const DELETE_PUBLISHER = 'DELETE_PUBLISHER';

// ================== SETTINGS ==================
const VIEW_SETTINGS = 'VIEW_SETTINGS';
const EDIT_SETTINGS = 'EDIT_SETTINGS';

// ================== PERMISSION ==================
const VIEW_PERMISSION = 'VIEW_PERMISSION';
const CREATE_PERMISSION = 'CREATE_PERMISSION';
const EDIT_PERMISSION = 'EDIT_PERMISSION';
const DELETE_PERMISSION = 'DELETE_PERMISSION';

// ================== PLAN ==================
const VIEW_PLAN = 'VIEW_PLAN';
const CREATE_PLAN = 'CREATE_PLAN';
const EDIT_PLAN = 'EDIT_PLAN';
const DELETE_PLAN = 'DELETE_PLAN';

// ================== PROFILE ==================
const VIEW_PROFILE = 'VIEW_PROFILE';
const EDIT_PROFILE = 'EDIT_PROFILE';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

module.exports = {
    MODIFY_ALL,
    VIEW_ALL,

    VIEW_DASHBOARD,

    VIEW_USER,
    CREATE_USER,
    EDIT_USER,
    DELETE_USER,

    VIEW_USER_ROLE,
    CREATE_USER_ROLE,
    EDIT_USER_ROLE,
    DELETE_USER_ROLE,
    ASSIGN_PERMISSION,

    VIEW_COMPANY,
    EDIT_COMPANY,

    VIEW_BOOK,
    CREATE_BOOK,
    EDIT_BOOK,
    DELETE_BOOK,

    VIEW_AUTHOR,
    CREATE_AUTHOR,
    EDIT_AUTHOR,
    DELETE_AUTHOR,

    VIEW_CATEGORY,
    CREATE_CATEGORY,
    EDIT_CATEGORY,
    DELETE_CATEGORY,

    VIEW_VENDOR,
    MANAGE_VENDOR,

    VIEW_PURCHASE,
    MANAGE_PURCHASE,

    VIEW_INVENTORY,
    MANAGE_INVENTORY,

    VIEW_BOOK_ISSUE,
    MANAGE_BOOK_ISSUE,

    REQUEST_BOOK,
    MANAGE_BOOK_REQUESTS,

    VIEW_BOOK_SUBMISSION,
    APPROVE_BOOK_SUBMISSION,
    REJECT_BOOK_SUBMISSION,

    VIEW_LIBRARY_MEMBER,
    CREATE_LIBRARY_MEMBER,
    EDIT_LIBRARY_MEMBER,
    DELETE_LIBRARY_MEMBER,

    VIEW_PUBLISHER,
    CREATE_PUBLISHER,
    EDIT_PUBLISHER,
    DELETE_PUBLISHER,

    VIEW_SETTINGS,
    EDIT_SETTINGS,

    VIEW_PERMISSION,
    CREATE_PERMISSION,
    EDIT_PERMISSION,
    DELETE_PERMISSION,

    VIEW_PLAN,
    CREATE_PLAN,
    EDIT_PLAN,
    DELETE_PLAN,

    VIEW_PROFILE,
    EDIT_PROFILE,
    CHANGE_PASSWORD
};
